version: "3.3"
services:
    solar_relog_api:
        build:
            context: SolarRelog/
            dockerfile: ./Dockerfile
        container_name: solar_relog_api
        restart: unless-stopped
        environment:
            - ASPNETCORE_URLS=http://+:5000
            - ASPNETCORE_ENVIRONMENT=Production
        volumes:
        - ./ProdDbs:/App/ProdDbs:rw
        ports:
            - 5000:5000